//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faturalar
    {
        public int FaturalarID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> AdresID { get; set; }
        public Nullable<int> PersonelID { get; set; }
    
        public virtual Personeller Personeller { get; set; }
        public virtual Siparisler Siparisler { get; set; }
        public virtual UyeAdresleri UyeAdresleri { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
