//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanyalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kampanyalar()
        {
            this.SiparisDetaylari = new HashSet<SiparisDetaylari>();
        }
    
        public int KampanyalarID { get; set; }
        public Nullable<int> indirimTuruID { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string KampanyaBasligi { get; set; }
        public string KampanyaAciklamasi { get; set; }
        public Nullable<System.DateTime> BaslamaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<int> PersonelID { get; set; }
    
        public virtual indirimTurleri indirimTurleri { get; set; }
        public virtual Personeller Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetaylari> SiparisDetaylari { get; set; }
    }
}
