//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kargolar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kargolar()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }
    
        public int KargolarID { get; set; }
        public Nullable<int> KargoFirmaID { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<decimal> KargoUcreti { get; set; }
        public Nullable<System.DateTime> KargoTeslimTarihi { get; set; }
    
        public virtual KargoFirmalari KargoFirmalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
    }
}
