//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlcuBirimleri
    {
        public int OlcuBirimleriID { get; set; }
        public string OlcuBirimiAdi { get; set; }
        public string Aciklama { get; set; }
    }
}
