//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklamlar
    {
        public int ReklamlarID { get; set; }
        public string ReklamAdi { get; set; }
        public string ReklamKodu { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Yer { get; set; }
        public Nullable<int> PersonelID { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
