//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sepet()
        {
            this.SepetDetay = new HashSet<SepetDetay>();
        }
    
        public int SepetlerID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<System.DateTime> Tarihi { get; set; }
        public Nullable<int> ToplamAdet { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SepetDetay> SepetDetay { get; set; }
    }
}
