//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunDuyurulari
    {
        public int UrunDuyurularID { get; set; }
        public Nullable<int> DuyuruID { get; set; }
        public Nullable<int> UrunID { get; set; }
    
        public virtual Duyurular Duyurular { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
