//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunOzellikleri
    {
        public int UrunOzelliklerID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string OzellikTanimi { get; set; }
        public string OlcuBirimi { get; set; }
        public Nullable<decimal> BirimStok { get; set; }
        public Nullable<decimal> KalanStok { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
