//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeAdresleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UyeAdresleri()
        {
            this.Faturalar = new HashSet<Faturalar>();
        }
    
        public int UyeAdresleriID { get; set; }
        public string AdresYeri { get; set; }
        public string Adres { get; set; }
        public string ili { get; set; }
        public string ilcesi { get; set; }
        public Nullable<int> UyeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faturalar> Faturalar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
