//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumlarID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string YorumBasligi { get; set; }
        public string YorumMetni { get; set; }
        public Nullable<int> Star { get; set; }
        public Nullable<System.DateTime> Tarihi { get; set; }
        public Nullable<int> BegenmeSayisi { get; set; }
        public Nullable<int> BegenmemeSayisi { get; set; }
        public Nullable<bool> OnayDurumu { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
